name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare repo
        uses: actions/checkout@master
      - name: prepare python
        uses: actions/setup-python@v2
          with: 
            python-version: '3.8'
      - name: Test
        uses: aaadlane/githubactiontest@master
